In [1]:
import cv2
import numpy
import os

In [2]:

img=cv2.imread('/home/pranavdheer/im.png')
print img.shape

(404, 614, 3)


In [3]:
cv2.startWindowThread()
cv2.namedWindow("preview")
cv2.imshow("preview", img)

In [3]:

gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
print gray.shape

(404, 614)


In [7]:
face_cascade.load('/home/pranavdheer/opencv-3.1.0/data/haarcascades/haarcascade_frontalface_default.xml')

True

In [4]:
face_cascade = cv2.CascadeClassifier('/home/pranavdheer/opencv-3.1.0/data/haarcascades/haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier('home/pranavdheer/opencv-3.1.0/data/haarcascades/haarcascade_eye.xml')

In [12]:
faces = face_cascade.detectMultiScale(gray)
l=[]
flag=0
print faces
for (x,y,w,h) in faces:
    cv2.rectangle(img,(x,y),(x+w,y+h),(0,0,255),2)
    f=gray[y:y+h,x:x+w]
    flag=flag+1
    l.append(f)
cv2.startWindowThread()
cv2.namedWindow("preview")
cv2.imshow("preview", img)

[[165  48  92  92]
 [434  85  95  95]
 [240 108 107 107]
 [326 100 121 121]]


In [6]:

for (x,y,w,h) in faces:
    cv2.putText(img,'faces',(x,y), cv2.FONT_HERSHEY_SIMPLEX  ,1,(255,0,0),2,cv2.LINE_AA)
cv2.startWindowThread()
cv2.namedWindow("preview")
cv2.imshow("preview", img)

In [13]:
import time

In [17]:
for ix in range (0,flag):
    f=l[ix]
    cv2.startWindowThread()
    cv2.namedWindow("preview") 
    cv2.imshow("preview", f)
    time.sleep(10)