In [1]:
import cv2
import numpy


In [2]:
img=cv2.imread('im.png')
print img.shape

(404, 614, 3)


In [3]:
cv2.startWindowThread()
cv2.namedWindow("preview")
cv2.imshow("preview", img)

In [5]:

gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
print gray.shape

(404, 614)


In [8]:
face_cascade.load('./OpenCV/data/haarcascades/haarcascade_frontalface_default.xml')

False

In [7]:
face_cascade = cv2.CascadeClassifier('./OpenCV/data/haarcascades/haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier('./OpenCV/data/haarcascades/haarcascade_eye.xml')

In [34]:
faces = face_cascade.detectMultiScale(gray)
print faces
for (x,y,w,h) in faces:
    cv2.rectangle(img,(x,y),(x+w,y+h),(0,0,255),2)
cv2.imshow('img',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[165  48  92  92]
 [434  85  95  95]
 [240 108 107 107]
 [326 100 121 121]]


In [10]:

for (x,y,w,h) in faces:
    cv2.putText(img,'faces',(x,y), cv2.FONT_HERSHEY_SIMPLEX  ,1,(255,0,0),2,cv2.LINE_AA)
cv2.imshow('img',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [35]:
f1=img[48:48+92,165:165+92]
f1_gray = cv2.cvtColor(f1, cv2.COLOR_BGR2GRAY)

In [37]:
cv2.imshow('face1',f1_gray)
cv2.waitKey(0)
cv2.destroyAllWindows()